# Generated by Django 2.0.4 on 2018-04-30 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('bookingid', models.AutoField(primary_key=True, serialize=False)),
                ('starttime', models.DateTimeField(null=True)),
                ('washoption', models.CharField(choices=[('WO', 'Wash Only'), ('WN', 'Wash & Naling Clipping'), ('DG', 'Deluxe Grooming')], default='WO', max_length=2)),
                ('instruction', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('dogid', models.AutoField(primary_key=True, serialize=False)),
                ('dogname', models.CharField(default='default', max_length=50)),
                ('dob', models.DateField(null=True)),
                ('breed', models.CharField(choices=[('GS', 'German Shepherd'), ('LR', 'Labrador Retriever'), ('GR', 'Golden Retriever'), ('RW', 'Rotteweiler'), ('BG', 'Beagle'), ('BD', 'Bulldog'), ('CW', 'Chihuahua'), ('PM', 'Pomeranian'), ('SH', 'Siberian Husky'), ('SS', 'Shetland Sheepdog'), ('OT', 'Other Breeds')], max_length=2, null=True)),
                ('xxx', models.CharField(max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DogGroom.Dog'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('client', 'dog', 'starttime')},
        ),
    ]
