# Generated by Django 2.0.4 on 2018-05-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DogGroom', '0007_auto_20180518_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='starttime',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
