# Generated by Django 2.0.4 on 2018-05-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DogGroom', '0008_auto_20180518_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='dogname',
            field=models.CharField(max_length=50),
        ),
    ]
